# Конфигурация Spanish Analyser
# Все настройки проекта (кроме паролей и API ключей)

# Настройки Anki
anki:
  # Путь к файлу коллекции Anki
  collection_path: "~/Library/Application Support/Anki2/User 1/collection.anki2"
  # Паттерн для поиска испанских колод
  deck_pattern: "Spanish*"
  # Режим проверки известности по лемме и части речи (вместо точного совпадения)
  # Если true, то "intersección" будет считаться известным, если в Anki есть "la intersección"
  # Если false, то "intersección" будет неизвестным, только "la intersección" - известным
  lemma_aware_known: true
  # Название типа заметок, который должен существовать в вашей коллекции Anki
  # Скрипт генерации .apkg через AnkiConnect найдёт его ID и будет использовать
  # существующую модель. Если тип не найден — выполнение завершится с ошибкой
  # и подсказками.
  note_type_name: "Spanish note type"
  # Названия полей для извлечения слов
  field_names:
    - "FrontText"
    - "BackText"
  # Минимальная доля испанских символов для выбора поля (от 0.0 до 1.0)
  min_spanish_ratio: 0.3

# Настройки анализа текста
text_analysis:
  # Минимальная длина слова для анализа
  min_word_length: 3
  # Максимальное количество слов для экспорта
  max_words_export: 1000
  # Включить определение частей речи
  enable_pos_tagging: true
  # Модель spaCy для испанского языка
  # Рекомендация: es_core_news_md — оптимальный баланс точности и скорости
  # При необходимости максимальной точности синтаксиса рассмотрите es_dep_news_trf (тяжёлая/медленная)
  spacy_model: "es_dep_news_trf"
  # Авто-скачивание модели при первом запуске (удобно для локальной работы)
  # Для CI/офлайн окружений можно выключить
  auto_download_spacy_model: true

# Настройки веб-скрапера
web_scraper:
  # Базовый URL для practicatest.com
  base_url: "https://practicatest.com"
  # Таймаут для HTTP запросов (в секундах)
  timeout: 30
  # User-Agent для веб-запросов
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"

# Настройки файлов
files:
  # Папка для загруженных HTML файлов
  downloads_folder: "data/downloads"
  # Папка для результатов анализа
  results_folder: "data/results"
  # Максимальное количество файлов результатов
  max_results_files: 20
  # Префикс для файлов результатов
  results_filename_prefix: "driving_tests_analysis"

# Настройки Excel экспорта
excel:
  # Формат относительной частоты (количество знаков после запятой)
  frequency_decimal_places: 4
  # Включить заголовки колонок
  include_headers: true
  # Название основного листа
  main_sheet_name: "Word Analysis"

# Настройки логирования
logging:
  # Уровень логирования для консоли (пользовательские сообщения)
  console_level: "INFO"
  # Уровень логирования для файла (технические детали)
  file_level: "DEBUG"
  # Формат логов
  format: "%(asctime)s - %(levelname)s - %(message)s"
  # Включить логирование в файл (с временными метками для каждой сессии)
  log_to_file: true
  # Путь к файлу логов (используется только если log_to_file=false, с timestamp)
  log_file: "logs/spanish_analyser_{timestamp}.log"
  # Максимальное количество файлов логов для хранения
  max_log_files: 10

# Настройки ИИ (OpenAI)
ai:
  # Модель OpenAI для генерации переводов BackText
  model: "gpt-5"
  # Доступные варианты моделей (для справки и выбора):
  # - gpt-5        — максимальное качество
  # - gpt-5-mini   — быстрее/дешевле, хороша для массовых задач
  # - gpt-5-nano   — самый дешевый вариант, но качество ниже
  # Параллельные запросы к OpenAI
  concurrency:
    # Сколько потоков реально использовать сейчас.
    # Рекомендация: начинать с 3–5 потоков, чтобы не получить 429 (rate limit).
    # Актуальные лимиты в вашем аккаунте и для выбранной модели смотрите в документации
    # OpenAI по квотам/лимитам:
    #   - Обзор: https://platform.openai.com/docs/guides/rate-limits/overview
    #   - Личные лимиты: https://platform.openai.com/account/rate-limits
    # Замечание: лимиты задаются в RPM/TPM и зависят от тарифа/истории, а не фиксированы «на 5 параллельных запросов».
    # Не повышайте значение резко — при частых 429 уменьшите число потоков.
    workers: 3
    
  # Управление rate limiting
  rate_limiting:
    # Базовая задержка между запросами (секунды)
    base_delay: 0.5
    # Максимальная задержка при rate limiting (секунды) 
    max_retry_delay: 15
    # Количество попыток при ошибках
    max_retries: 3

# Музыкальные настройки (фоновая 8-битная музыка в интерактивном меню)
music:
  # Включить чиптюн в интерактивном меню (true/false)
  chiptune_enabled: true
  # Доступные пресеты:
  # - cambio_groove: в духе Cambio Dolor, прогрессия D–Bm–G–A (64 шага)
  # - neo_pulse: в духе Matrix, минорный драйв Am–C–G–Em (64 шага)
  # - ambient_chips: спокойный фон Am–F–C–G (64 шага)
  # - nokia_classic: классический Nokia рингтон (Gran Vals) (48 шагов)
  # - tetris_theme: легендарная мелодия Тетриса (Korobeiniki) (64 шага)
  # - mario_theme: Super Mario Bros главная тема (64 шага)
  # - simple_mobile: простая мобильная мелодия в стиле 2000-х (64 шага)
  # - final_countdown: Europe - "The Final Countdown" в 8-битном стиле (80 шагов) 🎸
  # - boomer_mobile: алиас для simple_mobile (совместимость)
  # - matrix_neon: процедурный генератор в духе Matrix (длинный)
  chiptune_preset: "cambio_groove"
  # Темп: длительность ноты в секундах (меньше — быстрее)
  chiptune_tempo: 0.15
  # Длительность для процедурного пресета (секунды). Сгенерированный паттерн затем зацикливается.
  chiptune_duration: 150
  # Громкость (амплитуда) 0.01..0.5
  chiptune_amp: 0.15
  # Аудио-устройство: индекс (число) или имя (строка). null — устройство по умолчанию
  audio_device: null

# Кэширование
cache:
  # Корневая папка для кэша. Внутри создаются подпапки по типам.
  root_dir: "cache"
  # Максимальный размер для каждого подпула кэша (в МБ). При превышении будут удаляться старые записи.
  max_size_mb: 256

  # 1) HTML: кэш извлечённого текста из HTML/документов
  #    Влияние: ускоряет повторный анализ страниц; при слишком длинном TTL можно видеть устаревший текст
  #    Побочные эффекты: после обновления исходных HTML очистка произойдёт автоматически по сроку или вручную.
  html:
    enabled: true
    dir: "texts"      # подпапка: cache/texts
    ttl_days: 30      # срок жизни записей

  # 2) ANKI: кэш данных Anki (например, наборы известных слов, результаты запросов)
  #    Влияние: сокращает обращения к AnkiConnect; при длинном TTL новые/удалённые карточки могут не учитываться
  #    Побочные эффекты: после изменения колод рекомендуется дождаться TTL или вручную почистить подпапку.
  anki:
    enabled: true
    dir: "anki"       # подпапка: cache/anki
    ttl_days: 1

  # 3) spaCy: кэш результатов лемматизации/POS и др.
  #    Влияние: ускоряет повторные вычисления NLP; при смене версии модели возможно накопление «старого» кэша
  #    Побочные эффекты: при смене модели очистите подпапку spaCy.
  spacy:
    enabled: true
    dir: "spacy"      # подпапка: cache/spacy
    ttl_days: 60

  # 4) OpenAI: кэш результатов запросов к OpenAI API
  #    Влияние: экономит токены и время при повторных запросах; при длинном TTL могут использоваться устаревшие переводы
  #    Побочные эффекты: при смене модели или обновлении промптов рекомендуется очистить подпапку openai.
  openai:
    enabled: true
    dir: "openai"     # подпапка: cache/openai
    ttl_days: 7       # срок жизни записей

# Настройки тестирования
testing:
  enabled: true
  coverage:
    min_coverage: 0.8
  performance:
    enabled: true
  quality:
    # Минимальная точность POS-тегов в тестах качества
    min_pos_accuracy: 0.75
